"""Added is_active to Product model

Revision ID: 077a7e10b998
Revises: 177d6f0c71f2
Create Date: 2026-04-20 04:13:21.193667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077a7e10b998'
down_revision = '177d6f0c71f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
