"""added subscriber model

Revision ID: 177d6f0c71f2
Revises: c0be2b8486c7
Create Date: 2026-04-16 04:47:22.566841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177d6f0c71f2'
down_revision = 'c0be2b8486c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referer', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referer', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
