"""Add bank_id to Referer

Revision ID: 18e15a8643c0
Revises: fb37057a6cce
Create Date: 2026-02-05 10:37:13.059413
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e15a8643c0'
down_revision = 'fb37057a6cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - fixed ###
    # Update bank table
    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_bank_name', ['name'])

    # Update referer table: add bank_id with foreign key
    with op.batch_alter_table('referer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_referer_bank',  # <--- named constraint
            'bank',             # referenced table
            ['bank_id'],        # local column
            ['id']              # remote column
        )

    # Update staffs table
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.alter_column('documents',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - fixed ###
    # Revert staffs table
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.alter_column('documents',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # Revert referer table
    with op.batch_alter_table('referer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_referer_bank', type_='foreignkey')
        batch_op.drop_column('bank_id')

    # Revert bank table
    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bank_name', type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
