"""Add pickup_expired column to Order

Revision ID: 1a3e16b9ea8a
Revises: 5a0f6b8617ae
Create Date: 2026-02-14 09:13:26.203859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3e16b9ea8a'
down_revision = '5a0f6b8617ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_expired', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shifted', sa.Boolean(), nullable=True))
        batch_op.drop_column('pickup_used')
        batch_op.drop_column('delivered')
        batch_op.drop_column('items')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('delivered', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('pickup_used', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('shifted')
        batch_op.drop_column('pickup_expired')

    # ### end Alembic commands ###
