"""Add delivered column to Order

Revision ID: 53b1bceb5284
Revises: 1a3e16b9ea8a
Create Date: 2026-02-14 09:25:40.016919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b1bceb5284'
down_revision = '1a3e16b9ea8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivered')

    # ### end Alembic commands ###
