"""modified coupon code model

Revision ID: 775fe80d4def
Revises: 99d093179b2d
Create Date: 2026-05-02 03:07:04.419806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775fe80d4def'
down_revision = '99d093179b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
