"""Add unit column to Product

Revision ID: 7e67f604bfe1
Revises: d8105b90d1e5
Create Date: 2026-03-18 13:58:51.681005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e67f604bfe1'
down_revision = 'd8105b90d1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
