"""building catalog page

Revision ID: a9d62c3b02de
Revises: 077a7e10b998
Create Date: 2026-04-20 08:06:25.821180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d62c3b02de'
down_revision = '077a7e10b998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
