"""Added nullable password_hash and profile_image

Revision ID: c0be2b8486c7
Revises: f0298b9a35e7
Create Date: 2026-04-11 21:32:41.449781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0be2b8486c7'
down_revision = 'f0298b9a35e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_staffs')
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('password_hash')

    op.create_table('_alembic_tmp_staffs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('staff_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lga', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('nin', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bank_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('account_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=100), nullable=True),
    sa.Column('documents', sa.TEXT(), nullable=True),
    sa.Column('reset_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DATETIME(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rejection_reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nin'),
    sa.UniqueConstraint('staff_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
