"""Add terminated column to Order

Revision ID: d1ca21ba5c83
Revises: f9c9f4adef38
Create Date: 2026-02-16 12:32:34.222770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ca21ba5c83'
down_revision = 'f9c9f4adef38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('terminated')

    # ### end Alembic commands ###
