"""add color fields

Revision ID: f0298b9a35e7
Revises: 7e67f604bfe1
Create Date: 2026-03-21 05:00:39.484879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0298b9a35e7'
down_revision = '7e67f604bfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color_hex', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('color_hex')
        batch_op.drop_column('color_name')

    # ### end Alembic commands ###
