"""empty message

Revision ID: f9c9f4adef38
Revises: 53b1bceb5284
Create Date: 2026-02-16 11:10:08.566433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c9f4adef38'
down_revision = '53b1bceb5284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=120), nullable=True))
        batch_op.drop_column('approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
